import { sql } from "drizzle-orm";
import {
  pgTable,
  pgEnum,
  uuid,
  text,
  numeric,
  date,
  timestamp,
  uniqueIndex,
  index,
} from "drizzle-orm/pg-core";

// ---------- Enums ----------

export const appRole = pgEnum("app_role", [
  "super_admin",
  "admin",
  "encoder",
  "report_generator",
  "resident",
]);

export const residentStatus = pgEnum("resident_status", ["active", "inactive"]);

export const sentVia = pgEnum("sent_via", ["email", "sms", "printed", "hand_delivered"]);

export const receivedStatus = pgEnum("received_status", [
  "pending",
  "received",
  "acknowledged",
]);

export const paymentMode = pgEnum("payment_mode", [
  "cash",
  "cheque",
  "bank_transfer",
  "online",
]);

export const receivedBy = pgEnum("received_by", ["bank", "admin_office"]);

export const levyStatus = pgEnum("levy_status", ["active", "closed"]);

export const paymentStatus = pgEnum("payment_status", ["active", "voided"]);

// ---------- Tables ----------

/** Mirrors auth.users; role assignment + optional link to a resident (for future resident login). */
export const users = pgTable(
  "users",
  {
    id: uuid("id").primaryKey(), // == auth.users.id
    email: text("email").notNull().unique(),
    role: appRole("role"), // null until super_admin assigns one
    residentId: uuid("resident_id").references(() => residents.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("users_resident_id_idx").on(t.residentId)],
);

export const duesGroups = pgTable("dues_groups", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  name: text("name").notNull(),
  monthlyAmount: numeric("monthly_amount", { precision: 10, scale: 2 }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Full resident master record — contacts, dues assignment, status.
 * Aggregate SELECT on this table is restricted to super_admin via RLS (see policies.sql).
 * All other roles reach individual rows only through the resident_lookup() function.
 */
export const residents = pgTable(
  "residents",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    name: text("name").notNull(),
    unitNo: text("unit_no").notNull().unique(),
    duesGroupId: uuid("dues_group_id")
      .notNull()
      .references(() => duesGroups.id, { onDelete: "restrict" }),
    duesOverride: numeric("dues_override", { precision: 10, scale: 2 }),
    billingContact1: text("billing_contact_1"),
    billingContact2: text("billing_contact_2"),
    status: residentStatus("status").notNull().default("active"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("residents_dues_group_id_idx").on(t.duesGroupId)],
);

/** One row per resident per billing period. Generated by the generate_billing_run() function. */
export const billings = pgTable(
  "billings",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    residentId: uuid("resident_id")
      .notNull()
      .references(() => residents.id, { onDelete: "cascade" }),
    period: text("period").notNull(), // e.g. "Jul 2026"
    amount: numeric("amount", { precision: 10, scale: 2 }).notNull(),
    sentVia: sentVia("sent_via"),
    sentAt: date("sent_at"),
    receivedStatus: receivedStatus("received_status").notNull().default("pending"),
    receivedAt: date("received_at"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("billings_resident_period_idx").on(t.residentId, t.period),
    // Dashboard/Outstanding/Billing all filter billings by period alone; the
    // composite unique index above only helps when resident_id leads, so a
    // period-only WHERE was a full table scan without this.
    index("billings_period_idx").on(t.period),
  ],
);

/**
 * Regular monthly dues payments. Immutable once recorded — no UPDATE/DELETE
 * policy exists (see rls_policies.sql). Corrections go through the
 * void_payment() function, which flips status to 'voided' and stamps who/when/why;
 * the original row and its values are never altered. Aggregates (dashboard,
 * outstanding report, ledger totals) must filter status = 'active'; the
 * ledger view itself should still display voided rows, marked as such.
 */
export const payments = pgTable(
  "payments",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    residentId: uuid("resident_id")
      .notNull()
      .references(() => residents.id, { onDelete: "cascade" }),
    date: date("date").notNull(),
    amount: numeric("amount", { precision: 10, scale: 2 }).notNull(),
    mode: paymentMode("mode").notNull(),
    receivedBy: receivedBy("received_by").notNull(),
    period: text("period"),
    notes: text("notes"),
    status: paymentStatus("status").notNull().default("active"),
    voidedBy: uuid("voided_by").references(() => users.id, { onDelete: "set null" }),
    voidedAt: timestamp("voided_at", { withTimezone: true }),
    voidReason: text("void_reason"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // Ledger/Pay filter by resident_id; Dashboard's "collected this month"
    // filters by date range — both were unindexed full table scans.
    index("payments_resident_id_idx").on(t.residentId),
    index("payments_date_idx").on(t.date),
  ],
);

/**
 * How a payment's amount is spread across one or more billings — a payment
 * can span multiple bills (oldest-unpaid-first), and a bill can be paid
 * across multiple payments. Populated automatically by allocate_payment()
 * (SECURITY DEFINER), never written directly by the app. Any portion of a
 * payment that couldn't be allocated (no more unpaid bills at the time) is
 * simply unallocated — a credit, derived as payments.amount minus the sum
 * of its allocation rows, not stored separately.
 */
export const paymentAllocations = pgTable(
  "payment_allocations",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    paymentId: uuid("payment_id")
      .notNull()
      .references(() => payments.id, { onDelete: "cascade" }),
    billingId: uuid("billing_id")
      .notNull()
      .references(() => billings.id, { onDelete: "cascade" }),
    amount: numeric("amount", { precision: 10, scale: 2 }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("payment_allocations_payment_billing_idx").on(t.paymentId, t.billingId),
    // Ledger/Outstanding/Dashboard/Aging all sum allocations by billing_id
    // alone; the composite unique index only helps when payment_id leads.
    index("payment_allocations_billing_id_idx").on(t.billingId),
  ],
);

/** Only one levy may have status = 'active' at a time (enforced by the partial unique index below). */
export const levies = pgTable(
  "levies",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    name: text("name").notNull(),
    amountPerUnit: numeric("amount_per_unit", { precision: 10, scale: 2 }).notNull(),
    status: levyStatus("status").notNull().default("active"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("levies_single_active_idx")
      .on(t.status)
      .where(sql`${t.status} = 'active'`),
  ],
);

/**
 * Payments made against a levy. Immutable once recorded, same void_special_payment()
 * correction path as payments — see the comment above the `payments` table.
 */
export const specialPayments = pgTable(
  "special_payments",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    residentId: uuid("resident_id")
      .notNull()
      .references(() => residents.id, { onDelete: "cascade" }),
    levyId: uuid("levy_id")
      .notNull()
      .references(() => levies.id, { onDelete: "cascade" }),
    amount: numeric("amount", { precision: 10, scale: 2 }).notNull(),
    date: date("date").notNull(),
    mode: paymentMode("mode").notNull(),
    receivedBy: receivedBy("received_by").notNull(),
    status: paymentStatus("status").notNull().default("active"),
    voidedBy: uuid("voided_by").references(() => users.id, { onDelete: "set null" }),
    voidedAt: timestamp("voided_at", { withTimezone: true }),
    voidReason: text("void_reason"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("special_payments_resident_id_idx").on(t.residentId), index("special_payments_levy_id_idx").on(t.levyId)],
);
